name: s390x qemu tests (big-endian)

# The test suite takes ~50m to run so we only trigger it manually
on:
  release:
    types: [published]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  big-endian-qemu:
    runs-on: ubuntu-22.04

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Cache .ccache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: .ccache
        key: ${{ github.workflow }}-v1-${{ github.sha }}
        restore-keys: ${{ github.workflow }}-v1-

    - name: Get the qemu container
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Run tests
      run: >
        docker run --platform linux/s390x --rm --interactive --mount type=bind,source=$(pwd),target=/host s390x/alpine sh -c
        "
        apk add --update-cache g++ ninja cmake ccache sdl2-dev sdl2_image-dev fmt-dev libpng-dev jpeg-dev bzip2-dev gtest-dev wget &&
        cd /host &&
        export CCACHE_DIR=/host/.ccache &&
        cmake -S. -Bbuild -G Ninja -DNONET=ON -DNOSOUND=ON &&
        wget -nv -nc https://github.com/diasurgical/devilutionx-assets/releases/download/v2/spawn.mpq -P build &&
        cmake --build build -j $(nproc) &&
        ctest --test-dir build --output-on-failure -j $(nproc)
        "
