---
name: Nintendo Switch

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          tee /etc/apt/sources.list.d/bullseye-backports.list <<LIST
          deb http://deb.debian.org/debian bullseye-backports main
          LIST
          apt-get update
          apt-get install -y -t bullseye-backports cmake
          apt-get install -y --no-install-recommends --no-install-suggests \
            gettext

      - name: Configure CMake
        run: |
          cmake \
            -S . \
            -B build \
            -D CMAKE_BUILD_TYPE=RelWithDebInfo \
            -D CMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake

      - name: Build DevilutionX
        run: cmake --build build -j$(nproc)

      - name: Upload Package
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: devilutionx.nro
          path: ./build/devilutionx.nro

      - name: Update Release
        if: ${{ github.event_name == 'release' && !env.ACT }}
        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2
        with:
          asset_name: devilutionx-switch.nro
          file: ./build/devilutionx.nro
          overwrite: true
...
