name: Windows MSVC x64

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - '*.md'
      - 'docs/**'

permissions:
  contents: write

env:
  VCPKG_FEATURE_FLAGS: dependencygraph
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: ccache
      uses: hendrikmuhs/ccache-action@a1209f81afb8c005c13b4296c32e363431bffea5 # v1.2.17

    - name: Install latest CMake
      uses: lukka/get-cmake@57c20a23a6cac5b90f31864439996e5b206df9dc # latest

    - name: Restore or setup vcpkg
      uses: lukka/run-vcpkg@5e0cab206a5ea620130caf672fce3e4a6b5666a1 # v11.5
      with:
        vcpkgGitCommitId: '533a5fda5c0646d1771345fb572e759283444d5f'

    - name: Fetch test data
      run: |
          mkdir build-ninja-vcpkg-relwithdebinfo
          Invoke-WebRequest -Uri "https://github.com/diasurgical/devilutionx-assets/releases/download/v2/spawn.mpq" -OutFile "build-ninja-vcpkg-relwithdebinfo/spawn.mpq" -Resume

    - name: Get CMakePresets.json
      run: cp Packaging/windows/CMakePresets.json .

    - name: Run CMake consuming CMakePresets.json and vcpkg.json by mean of vcpkg.
      uses: lukka/run-cmake@af1be47fd7c933593f687731bc6fdbee024d3ff4 # v10.8
      with:
        configurePreset: 'ninja-vcpkg-relwithdebinfo'
        buildPreset: 'ninja-vcpkg-relwithdebinfo'
        testPreset: 'ninja-vcpkg-relwithdebinfo'

    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: devilutionx.exe
        path: |
            build-ninja-vcpkg-relwithdebinfo/devilutionx.exe
            build-ninja-vcpkg-relwithdebinfo/bz2.dll
            build-ninja-vcpkg-relwithdebinfo/fmt.dll
            build-ninja-vcpkg-relwithdebinfo/libpng16.dll
            build-ninja-vcpkg-relwithdebinfo/libsodium.dll
            build-ninja-vcpkg-relwithdebinfo/SDL2.dll
            build-ninja-vcpkg-relwithdebinfo/SDL2_image.dll
            build-ninja-vcpkg-relwithdebinfo/zlib1.dll
