name: Xbox One / Series

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  release:
    types: [published]
    paths-ignore:
      - '*.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: ccache
      uses: hendrikmuhs/ccache-action@a1209f81afb8c005c13b4296c32e363431bffea5 # v1.2.17

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0
      with:
        msbuild-architecture: x64

    - name: Configure git
      shell: cmd
      run: |
        git config --global core.filemode false
        git config --global core.autocrlf false

    - name: Install gettext
      run: >
        New-Item -Path . -Name tools-gettext -ItemType Directory -Force &&
        Invoke-WebRequest -Uri "https://github.com/vslavik/gettext-tools-windows/releases/download/v0.22.5/gettext-tools-windows-0.22.5.zip" -OutFile tools-gettext.zip -Resume &&
        Expand-Archive tools-gettext.zip &&
        Remove-Item tools-gettext.zip &&
        Add-Content $env:GITHUB_PATH "$((Get-Item tools-gettext).FullName)\bin"

    - name: Build
      shell: cmd
      run: |
        cd ${{ github.workspace }}\Packaging\xbox-one
        build.bat

    - name: Copy artifacts to package directory
      run: >
        New-Item -Path build\uwp-project -Name pkg -ItemType Directory -Force &&
        Get-Childitem -Path build\uwp-project\AppxPackages, build\uwp-project\Release
        -Include Microsoft.VCLibs.x64.*.appx, devilutionX_*_x64.appx -File -Recurse |
        Copy-Item -Destination build\uwp-project\pkg\

    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: devilutionx-xbox-one-series
        if-no-files-found: error
        path: |
          build/uwp-project/pkg/

    - name: Package Release
      if: ${{ github.event_name == 'release' && !env.ACT }}
      working-directory: ${{github.workspace}}/build/uwp-project/pkg/
      run: 7z a -r ../../../devilutionx-xbox-one-series.zip .

    - name: Update Release
      if: ${{ github.event_name == 'release' && !env.ACT }}
      uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2
      with:
        file: devilutionx-xbox-one-series.zip
        overwrite: true
